### ISSUE TITLE
TODO: use Rust to implement RPC APIs

### ISSUE THREAD

**Issue by coderfox** [SANDRAProject/api#5]
- [ ] provide RPC API to replace REST API
- [ ] rewrite server in Rust
- [ ] create API Gateway in Rust
